[package]
name = "nrf52840-blink"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"]  }
cortex-m-rt = "0.7.5"
defmt = "0.3.10"
embedded-hal = "1.0.0"
nrf52840-hal = "0.18.0"
